### ISSUE TITLE
django 1.4 compatibility

### ISSUE THREAD

**Issue by ayalalazaro** [explorerhq/sql-explorer#90]
I have followed the installation procedure but when I run manage.py syncdb I get the following error:
AttributeError: 'Settings' object has no attribute 'AUTH_USER_MODEL'

I googled it and it seems that the attribute AUTH_USER_MODEL was first introduced in django in version 1.5.
Is there a way to make it work with 1.4?

Thanks
